import { PartData, Lens } from './types';

export const LENSES: Lens[] = [
  { id: 'institutionalLogic', name: 'Institutional Logic', emoji: '🏛️', color: 'border-sky-500' },
  { id: 'narrativePower', name: 'Narrative Power', emoji: '📖', color: 'border-indigo-500' },
  { id: 'psychologicalDynamics', name: 'Psychological Dynamics', emoji: '🧠', color: 'border-purple-500' },
  { id: 'humanAgency', name: 'Human Agency', emoji: '👤', color: 'border-rose-500' },
  { id: 'informationControl', name: 'Information Control', emoji: 'ℹ️', color: 'border-amber-500' },
  { id: 'artisticPoetic', name: 'Artistic / Poetic', emoji: '🎨', color: 'border-teal-500' },
  { id: 'rhetoricalTone', name: 'Rhetorical / Tone', emoji: '🗣️', color: 'border-emerald-500' },
  { id: 'philosophicalEpistemic', name: 'Philosophical / Epistemic', emoji: '💡', color: 'border-yellow-500' },
  { id: 'synthesis', name: 'Synthesis', emoji: '✨', color: 'border-slate-400' },
];

export const MATRIX_DATA: PartData[] = [
  {
    id: 1,
    title: 'From Statist Faith to Praxeological Awakening',
    chapters: [
      { id: 'p1c0', part: 1, chapter: 0, title: 'Stage Setting', lenses: { institutionalLogic: 'Promise of - Implied machinery behind experience', narrativePower: 'Tension, anticipation<br>- story<br>- Introduction of sacred myths', psychologicalDynamics: 'Premonition of rupture<br>- Implicit invitation to choose<br>- Reader as actor', humanAgency: 'Fog lifting<br>- Implicit invitation to choose', informationControl: 'Tone-setting: euphemism vs. clarity', artisticPoetic: 'Morpheus-like cadence', rhetoricalTone: 'Weight in silence Direct, calm address', philosophicalEpistemic: 'What is real? How do I know?' }, synthesis: 'This is not a story about ideology — it is a story about awakening. The ground will shake; the myths will dissolve; the reader is warned but not begged. Proceed only if you wish to act.', status: 'review', revisionFlags: [{type: 'Tone', emoji: '🗣️'}, {type: 'Epistemic', emoji: '💡'}], previewText: 'A warning to the reader that this story is about awakening, not ideology.'},
      { id: 'p1c1', part: 1, chapter: 1, title: 'I Was There', lenses: { institutionalLogic: 'Security myth<br>- State unable to fulfill basic functions<br>- collapses', narrativePower: 'Shock, moral rupture<br>- The gap between media narrative and lived reality', psychologicalDynamics: 'First-hand disillusionment<br>- Inner detachment begins', humanAgency: 'The seen vs. the believed', informationControl: 'Institutions exposed', artisticPoetic: 'Echoes of an old song jargon', rhetoricalTone: 'Plainspoken, confessional, stripped of<br>- First flicker of the "I"', philosophicalEpistemic: 'False promises break' }, synthesis: 'The rupture is personal, not theoretical. When reality crashes the myth, it isn\'t academic — it\'s visceral. And from that wound, thought begins.', status: 'final', revisionFlags: [], previewText: 'The moment personal experience shatters the official narrative.' },
      { id: 'p1c2', part: 1, chapter: 2, title: 'How We Were Raised', lenses: { institutionalLogic: 'Zionism<br>- Childhood rituals: anthem, holidays<br>- State as parent', narrativePower: 'Fear shaping identity<br>- as sacred origin tale<br>- Founding myths internalized', psychologicalDynamics: 'Obedience as safety<br>- "We were born into this song"', humanAgency: 'No authorship — inherited belief sanitized early', informationControl: 'Hasbara at the playground<br>- school', artisticPoetic: 'Tone of reflective sorrow', rhetoricalTone: 'Belief precedes truth', philosophicalEpistemic: 'Reality<br>- Indoctrination is not a bug — it is the software.' }, synthesis: 'What we thought was home was a stage.', status: 'draft', revisionFlags: [], previewText: 'Examining the childhood indoctrination into a statist narrative.' },
      { id: 'p1c3', part: 1, chapter: 3, title: 'It Felt Just', lenses: { institutionalLogic: 'Myths moralize the<br>- Institutional logic made emotionally appealing structure', narrativePower: 'Sincere moral alignment<br>- Duty becomes righteousness', psychologicalDynamics: 'Pride in obedience<br>- No awareness of alternative', humanAgency: 'Volition eclipsed by belief', informationControl: 'Language of justice co-opted', artisticPoetic: '"The uniforms felt clean"', rhetoricalTone: 'Earnest, almost tragic tone', philosophicalEpistemic: 'Justice<br>- Volition is illusion' }, synthesis: 'You must understand: we didn\'t obey out of fear — we obeyed because we believed it was right. That is how deep the trap runs.', status: 'review', revisionFlags: [{type: 'Logic', emoji: '🔁'}], previewText: 'The psychological state of believing obedience is righteousness.' },
      { id: 'p1c4', part: 1, chapter: 4, title: 'Wearing the Uniform', lenses: { institutionalLogic: 'Military - Draft is normalized<br>- Obedience ritualized', narrativePower: 'Role-play becomes self<br>- mythos activates pride and silence', psychologicalDynamics: 'Conflict buried deep<br>- Identity surrendered to the role', humanAgency: 'Can agency survive ritualized coercion?', informationControl: 'Hero-villain dichotomy reinforced', artisticPoetic: '"Marching in someone else\'s body" tone', rhetoricalTone: 'Sharp, clinical', philosophicalEpistemic: 'To wear the uniform is to disappear. You feel strong, but you are gone.' }, synthesis: 'To wear the uniform is to disappear. You feel strong, but you are gone.', status: 'final', revisionFlags: [], previewText: 'The surrender of self and identity to a uniform and role.' },
      { id: 'p1c5', part: 1, chapter: 5, title: 'Didn\'t Add Up', lenses: { institutionalLogic: 'Cracks in - Controlled media - Official logic falters', narrativePower: 'Dissonance gnaws quietly<br>- Inconsistencies accumulate the master story', psychologicalDynamics: 'Whispers of contradiction<br>- Inner voice flickers<br>- Doubt as proto-agency', humanAgency: 'Logic begins to reassert', informationControl: 'Can\'t patch every hole', artisticPoetic: '"The myth stuttered"', rhetoricalTone: 'Inquisitive', philosophicalEpistemic: 'The myth never breaks all at once. It unravels, quietly, like an old thread pulled from a uniform.' }, synthesis: 'The myth never breaks all at once. It unravels, quietly, like an old thread pulled from a uniform.', status: 'draft', revisionFlags: [], previewText: 'The slow, quiet unraveling of a foundational myth.' },
      { id: 'p1c6', part: 1, chapter: 6, title: 'It Got Personal', lenses: { institutionalLogic: 'Myth collides - Sanitized narrative breaks - Institution\'s actions harm the believer', narrativePower: 'Trauma, shame, confusion<br>- "Blood stains don\'t wash from dreams"', psychologicalDynamics: 'Psychic rupture<br>- First break from identification', humanAgency: 'Subject becomes object of state power', informationControl: 'Lived pain under real violence', artisticPoetic: 'Intimate, raw tone', rhetoricalTone: 'The awakening begins in pain.', philosophicalEpistemic: 'What was once your story now crushes you.' }, synthesis: 'The awakening begins in pain. What was once your story now crushes you.', status: 'review', revisionFlags: [{type: 'Poetic', emoji: '🎨'}, {type: 'Tone', emoji: '🗣️'}], previewText: 'The moment the abstract myth inflicts personal, concrete pain.' },
      { id: 'p1c7', part: 1, chapter: 7, title: 'No One\'s in Charge', lenses: { institutionalLogic: 'Collapse of moral legitimacy - The system is automated<br>- "Empty control towers"', narrativePower: 'Fractured identity<br>- No villain, just mechanism', psychologicalDynamics: 'Hollowed-out belief<br>- Freedom felt as absence, not power', humanAgency: 'Void-like, analytical tone', informationControl: 'Media can\'t explain chaos', artisticPoetic: 'Power without purpose is dead logic', rhetoricalTone: 'Void-like, analytical tone', philosophicalEpistemic: 'The truth is worse than evil — it\'s emptiness. No one\'s steering the machine. It just feeds.' }, synthesis: 'The truth is worse than evil — it\'s emptiness. No one\'s steering the machine. It just feeds.', status: 'final', revisionFlags: [], previewText: 'The horrifying realization that the system is an empty, automated mechanism.' },
      { id: 'p1c8', part: 1, chapter: 8, title: 'I Had to Understand', lenses: { institutionalLogic: 'From state to structure<br>- From structure to logic', narrativePower: 'Desperate need for sense<br>- Story turns inward<br>- Personal myth deconstructed', psychologicalDynamics: 'From victim to seeker<br>- Filters removed', humanAgency: 'First conscious<br>- "I stepped outside the frame"', informationControl: 'Raw search begins', artisticPoetic: 'Tone shifts: declarative, controlled choice', rhetoricalTone: 'Declarative, controlled choice<br>- "I want to know"', philosophicalEpistemic: 'Volition as epistemic threshold' }, synthesis: 'This was the first true act. Not rebellion, not ideology. Just this: I chose to see.', status: 'final', revisionFlags: [], previewText: 'The first conscious act of agency: the choice to see and understand.' },
    ],
  },
  {
    id: 2,
    title: 'A Praxeological Autopsy: From Life to State',
    chapters: [
      { id: 'p2c9', part: 2, chapter: 9, title: 'Life', lenses: { institutionalLogic: 'Biological grounding', narrativePower: 'Creation myth reinterpreted', psychologicalDynamics: 'Self-awareness awakens', humanAgency: '"I live, therefore I act"', informationControl: 'Survival instincts', artisticPoetic: '"Heartbeat of Foundational, still logic"', rhetoricalTone: 'Pure perception', philosophicalEpistemic: 'Precondition of action<br>- Ontological primacy of' }, synthesis: 'To live is to act. This is the beginning of all structure — not life, but action as axiomatic political, but existential.', status: 'review', revisionFlags: [{type: 'Epistemic', emoji: '💡'}], previewText: 'The axiom that life necessitates action, the foundation of all that follows.'},
      { id: 'p2c10', part: 2, chapter: 10, title: 'Choice', lenses: { institutionalLogic: 'Alternatives imply limits<br>- Cost implies scarcity', narrativePower: '"Choose the state or be chaos"<br>- "Forks in the soul"', psychologicalDynamics: 'Fear of error vs. thrill of freedom', humanAgency: 'Volition as a real force<br>- Every choice affirms your existence as an author', informationControl: 'First break from the collective script', artisticPoetic: 'Turing test of agency', rhetoricalTone: 'Clean, methodical', philosophicalEpistemic: 'Freedom presupposes limits - or denies it.' }, synthesis: 'Every choice affirms your existence as an author of your path - or denies it.', status: 'draft', revisionFlags: [], previewText: 'Choice as the fundamental act of authorship over one\'s own life.' },
      { id: 'p2c11', part: 2, chapter: 11, title: 'Action', lenses: { institutionalLogic: 'Means, ends, plans<br>- Structure emerges', narrativePower: 'The hero begins to act', psychologicalDynamics: 'Inner alignment<br>- Confusing action with rebellion', humanAgency: 'Sovereign chooser', informationControl: '"Muscles of meaning"', artisticPoetic: 'Conscious purpose', rhetoricalTone: 'Declarative', philosophicalEpistemic: 'Teleology, causality, intentionality' }, synthesis: 'Action is not reaction. It is creation with intent.', status: 'final', revisionFlags: [], previewText: 'Defining action as intentional creation, not mere reaction.' },
      { id: 'p2c12', part: 2, chapter: 12, title: 'Interaction', lenses: { institutionalLogic: 'Voluntary exchange<br>- Emergent order', narrativePower: 'Tribal boundaries form - "Echoes of goodwill"', psychologicalDynamics: 'Trust vs. suspicion', humanAgency: 'Society as contract, not organism', informationControl: 'Ideological filters on \'the other\'', artisticPoetic: 'Exploratory', rhetoricalTone: 'Reciprocity', philosophicalEpistemic: 'Where action meets action, society forms — not from law, but from choice.' }, synthesis: 'Where action meets action, society forms — not from law, but from choice.', status: 'draft', revisionFlags: [], previewText: 'The emergence of society from voluntary interaction, not from top-down law.' },
      { id: 'p2c13', part: 2, chapter: 13, title: 'Coercion', lenses: { institutionalLogic: '"Words under knives"', narrativePower: 'Force overrides dialogue', psychologicalDynamics: 'Fear, guilt, silence', humanAgency: 'Moral thresholds crossed', informationControl: 'Language shifts to justify violence', artisticPoetic: 'Critical, cold', rhetoricalTone: 'Power vs. persuasion', philosophicalEpistemic: 'When persuasion fails, power steps in. Coercion is not policy — it is war on agency.' }, synthesis: 'When persuasion fails, power steps in. Coercion is not policy — it is war on agency.', status: 'review', revisionFlags: [{type: 'Tone', emoji: '🗣️'}], previewText: 'Identifying coercion as the failure of persuasion and an assault on agency.' },
      { id: 'p2c14', part: 2, chapter: 14, title: 'State', lenses: { institutionalLogic: 'Obedience normalized<br>- Institutionalized coercion', narrativePower: 'Authority moralized - Mythology of law and order', psychologicalDynamics: 'Abdication of agency', humanAgency: 'Structure replaces thought', informationControl: 'State as father/guardian', artisticPoetic: '"The iron myth"', rhetoricalTone: 'Forensic', philosophicalEpistemic: 'The state is coercion with a costume — legitimacy dressed as law.' }, synthesis: 'The state is coercion with a costume — legitimacy dressed as law epistemology.', status: 'final', revisionFlags: [], previewText: 'Defining the state as coercion legitimized through ritual and myth.' },
      { id: 'p2c15', part: 2, chapter: 15, title: 'War', lenses: { institutionalLogic: 'Trauma as national logic - Ultimate statist expression', narrativePower: 'Sacred war stories persist - "Drums from within"', psychologicalDynamics: 'Agent reduced to instrument', humanAgency: 'War as the failure of action and thought', informationControl: 'Euphemism at maximum', artisticPoetic: 'Grave, austere', rhetoricalTone: 'War is not the exception to the state — it is its climax.', philosophicalEpistemic: 'War is not the exception to the state — it is its climax.' }, synthesis: 'War is not the exception to the state — it is its climax.', status: 'final', revisionFlags: [], previewText: 'Positioning war as the ultimate and logical expression of the state.' },
    ]
  },
  {
    id: 3,
    title: 'Statism in the Holy Land: A Live Case Study',
    chapters: [
      { id: 'p3c16', part: 3, chapter: 16, title: 'Myths', lenses: { institutionalLogic: 'Hasbara as enforcement of - Identity built on chosen people complex', narrativePower: 'Masada, Holocaust, Exodus<br>- Sacred trauma', psychologicalDynamics: 'Critique framed as betrayal', humanAgency: 'Myth as proto-ideology', informationControl: 'Myths used to legitimize power', artisticPoetic: '"We walk through echoes"', rhetoricalTone: 'Reverent, mythical', philosophicalEpistemic: 'The state feeds on story. Myth is not its tool — it is its womb.' }, synthesis: 'The state feeds on story. Myth is not its tool — it is its womb.', status: 'draft', revisionFlags: [], previewText: 'Analyzing how the state uses myth as its foundational reproductive organ.' },
      { id: 'p3c17', part: 3, chapter: 17, title: 'Legitimacy', lenses: { institutionalLogic: 'Divine right + democracy', narrativePower: 'Obedience as virtue', psychologicalDynamics: 'Doubt suppressed', humanAgency: 'Consent vs. legitimacy', informationControl: 'Faith rewarded', artisticPoetic: '"Crowns on mannequins"', rhetoricalTone: 'Ironic, probing', philosophicalEpistemic: 'Legitimacy is not consent — it is performance, repeated until believed.' }, synthesis: 'Legitimacy is not consent — it is performance, repeated until believed.', status: 'review', revisionFlags: [{type: 'Epistemic', emoji: '💡'}], previewText: 'Deconstructing legitimacy as a performance rather than genuine consent.' },
      { id: 'p3c18', part: 3, chapter: 18, title: 'Institutions', lenses: { institutionalLogic: 'Cartel structures, - Bureaucratic euphemisms', narrativePower: '"Startup Nation" myth', psychologicalDynamics: 'Volition confused for loyalty', humanAgency: 'Institutional entropy', informationControl: 'Gratitude traps incentives skewed', artisticPoetic: '"Shiny cages"', rhetoricalTone: 'Clinical', philosophicalEpistemic: 'When institutions mask themselves as success stories, decay becomes invisible.' }, synthesis: 'When institutions mask themselves as success stories, decay becomes invisible.', status: 'draft', revisionFlags: [{type: 'Logic', emoji: '🔁'}], previewText: 'How institutions use success narratives to mask internal decay.' },
      { id: 'p3c19', part: 3, chapter: 19, title: 'The Army', lenses: { institutionalLogic: 'Draft system, - Hero-villain language', narrativePower: 'Moral military fantasy', psychologicalDynamics: 'Agency replaced by identity', humanAgency: 'Coercion sanctified', informationControl: 'Trauma as bonding structure of force', artisticPoetic: '"March of masks"', rhetoricalTone: 'Dual-tone: reverent vs. cold', philosophicalEpistemic: 'The army isn\'t just defense — it\'s the moral factory of statism.' }, synthesis: 'The army isn\'t just defense — it\'s the moral factory of statism.', status: 'final', revisionFlags: [], previewText: 'Presenting the army not just as a defense force, but as the state\'s primary moral factory.' },
      { id: 'p3c20', part: 3, chapter: 20, title: 'Media', lenses: { institutionalLogic: 'Censorship, narrative policing', narrativePower: 'Constructed enemies, sacred victims', psychologicalDynamics: 'Dissent internalized - Perpetual fear as norm', humanAgency: 'Control of epistemology', informationControl: 'Media aligned with state goals', artisticPoetic: '"Words wrapped in wire"', rhetoricalTone: 'Razor-sharp', philosophicalEpistemic: 'The media no longer informs — it disciplines.' }, synthesis: 'The media no longer informs — it disciplines.', status: 'final', revisionFlags: [], previewText: 'When the media transitions from a tool of information to a tool of discipline.' },
      { id: 'p3c21', part: 3, chapter: 21, title: 'Trauma', lenses: { institutionalLogic: 'Commemoration as indoctrination - National trauma becomes identity', narrativePower: 'Personal pain absorbed into myth - Sacred wounds maintained', psychologicalDynamics: 'Trauma-politics loop', humanAgency: 'Trauma as collective trance', informationControl: '"Altars of pain"', artisticPoetic: 'Raw, elegiac', rhetoricalTone: 'In the name of remembrance, freedom is forgotten.', philosophicalEpistemic: 'In the name of remembrance, freedom is forgotten.' }, synthesis: 'In the name of remembrance, freedom is forgotten.', status: 'review', revisionFlags: [{type: 'Poetic', emoji: '🎨'}], previewText: 'How national trauma is weaponized to enforce identity and sacrifice freedom.' },
    ]
  },
  {
    id: 4,
    title: 'Reclaiming Agency in a Post-Statist World',
    chapters: [
      { id: 'p4c22', part: 4, chapter: 22, title: 'Recovery', lenses: { institutionalLogic: 'Acknowledging past surrender', narrativePower: 'Systems recede', psychologicalDynamics: 'Integration of trauma', humanAgency: 'Past does not define the actor', informationControl: 'De-mythologizing begins', artisticPoetic: '"Sun through"', rhetoricalTone: 'Soft, clarifying tone', philosophicalEpistemic: 'Language detoxcracks' }, synthesis: 'Recovery is not return — it is reckoning.', status: 'draft', revisionFlags: [], previewText: 'Defining recovery not as a return to a past state, but a reckoning with it.' },
      { id: 'p4c23', part: 4, chapter: 23, title: 'N/A', lenses: { institutionalLogic: 'Ethics as - Silencing old frames', narrativePower: 'Self-story rebuilt - From fear to courage', psychologicalDynamics: 'Reawakening choice', humanAgency: 'Volition is not belief - it is authorship', informationControl: 'N/A - Truth replaces myth', artisticPoetic: '"Clean flame"', rhetoricalTone: 'Firm, self-spoken', philosophicalEpistemic: 'Personal logic' }, synthesis: 'Volition is not belief - it is authorship personal logic.', status: 'draft', revisionFlags: [{type: 'Logic', emoji: '🔁'}], previewText: 'Distinguishing true volition as authorship, not simply belief.' },
      { id: 'p4c24', part: 4, chapter: 24, title: 'Clarity', lenses: { institutionalLogic: 'New moral structure', narrativePower: 'Lightness, coherence', psychologicalDynamics: 'Reality reclaimed from dogma', humanAgency: 'Truth reasserts', informationControl: '"No more riddles"', artisticPoetic: 'Transparent', rhetoricalTone: 'N/A', philosophicalEpistemic: 'Clarity is not found — it is built.' }, synthesis: 'Clarity is not found — it is built.', status: 'review', revisionFlags: [{type: 'Epistemic', emoji: '💡'}], previewText: 'Clarity as a constructed state, not a found object.' },
      { id: 'p4c25', part: 4, chapter: 25, title: 'Decentralization', lenses: { institutionalLogic: 'Local, voluntary structures', narrativePower: 'Fragmented stories - Trust rebuilt', psychologicalDynamics: 'Hopeful, open', humanAgency: '"Web of lives"', informationControl: 'Bureaucracy withdrawn', artisticPoetic: 'N/A', rhetoricalTone: 'N/A', philosophicalEpistemic: 'Power withdrawn, trust returns.' }, synthesis: 'Power withdrawn, trust returns.', status: 'draft', revisionFlags: [], previewText: 'The relationship between the withdrawal of centralized power and the return of trust.' },
      { id: 'p4c26', part: 4, chapter: 26, title: 'Parallel Struct.', lenses: { institutionalLogic: 'Order as emergent - Control reduced', narrativePower: 'Alternatives arise from choice', psychologicalDynamics: 'Healing through participation', humanAgency: '"New soil" - Confident', informationControl: 'Non-coercive platforms', artisticPoetic: 'Organic narratives form', rhetoricalTone: 'N/A', philosophicalEpistemic: 'Spontaneous systems' }, synthesis: 'The future grows quietly beside the ruins.', status: 'draft', revisionFlags: [], previewText: 'Observing how new, voluntary structures grow alongside decaying old ones.' },
      { id: 'p4c27', part: 4, chapter: 27, title: 'Liberation', lenses: { institutionalLogic: 'Full restoration of authorship', narrativePower: 'Joy, resolve, clarity', psychologicalDynamics: 'Life beyond the state identity', humanAgency: '"Silence becomes speech"', informationControl: 'Propaganda no longer needed', artisticPoetic: 'Uplifted, resolved', rhetoricalTone: 'Post-statist', philosophicalEpistemic: 'Sovereignty of the soul' }, synthesis: 'To be free is to be fully real — again.', status: 'final', revisionFlags: [], previewText: 'Defining ultimate liberation as the complete restoration of one\'s reality and authorship.' },
    ]
  }
];