services:
  - type: web
    name: matrix-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
